/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class Span : TBase
{
  private long _trace_id;
  private string _name;
  private long _id;
  private long _parent_id;
  private List<Annotation> _annotations;
  private List<BinaryAnnotation> _binary_annotations;
  private bool _debug;

  public long Trace_id
  {
    get
    {
      return _trace_id;
    }
    set
    {
      __isset.trace_id = true;
      this._trace_id = value;
    }
  }

  public string Name
  {
    get
    {
      return _name;
    }
    set
    {
      __isset.name = true;
      this._name = value;
    }
  }

  public long Id
  {
    get
    {
      return _id;
    }
    set
    {
      __isset.id = true;
      this._id = value;
    }
  }

  public long Parent_id
  {
    get
    {
      return _parent_id;
    }
    set
    {
      __isset.parent_id = true;
      this._parent_id = value;
    }
  }

  public List<Annotation> Annotations
  {
    get
    {
      return _annotations;
    }
    set
    {
      __isset.annotations = true;
      this._annotations = value;
    }
  }

  public List<BinaryAnnotation> Binary_annotations
  {
    get
    {
      return _binary_annotations;
    }
    set
    {
      __isset.binary_annotations = true;
      this._binary_annotations = value;
    }
  }

  public bool Debug
  {
    get
    {
      return _debug;
    }
    set
    {
      __isset.debug = true;
      this._debug = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool trace_id;
    public bool name;
    public bool id;
    public bool parent_id;
    public bool annotations;
    public bool binary_annotations;
    public bool debug;
  }

  public Span() {
    this._debug = false;
    this.__isset.debug = true;
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I64) {
            Trace_id = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.String) {
            Name = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 4:
          if (field.Type == TType.I64) {
            Id = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 5:
          if (field.Type == TType.I64) {
            Parent_id = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 6:
          if (field.Type == TType.List) {
            {
              Annotations = new List<Annotation>();
              TList _list0 = iprot.ReadListBegin();
              for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
              {
                Annotation _elem2;
                _elem2 = new Annotation();
                _elem2.Read(iprot);
                Annotations.Add(_elem2);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 8:
          if (field.Type == TType.List) {
            {
              Binary_annotations = new List<BinaryAnnotation>();
              TList _list3 = iprot.ReadListBegin();
              for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
              {
                BinaryAnnotation _elem5;
                _elem5 = new BinaryAnnotation();
                _elem5.Read(iprot);
                Binary_annotations.Add(_elem5);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 9:
          if (field.Type == TType.Bool) {
            Debug = iprot.ReadBool();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("Span");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.trace_id) {
      field.Name = "trace_id";
      field.Type = TType.I64;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Trace_id);
      oprot.WriteFieldEnd();
    }
    if (Name != null && __isset.name) {
      field.Name = "name";
      field.Type = TType.String;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Name);
      oprot.WriteFieldEnd();
    }
    if (__isset.id) {
      field.Name = "id";
      field.Type = TType.I64;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Id);
      oprot.WriteFieldEnd();
    }
    if (__isset.parent_id) {
      field.Name = "parent_id";
      field.Type = TType.I64;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Parent_id);
      oprot.WriteFieldEnd();
    }
    if (Annotations != null && __isset.annotations) {
      field.Name = "annotations";
      field.Type = TType.List;
      field.ID = 6;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, Annotations.Count));
        foreach (Annotation _iter6 in Annotations)
        {
          _iter6.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    if (Binary_annotations != null && __isset.binary_annotations) {
      field.Name = "binary_annotations";
      field.Type = TType.List;
      field.ID = 8;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, Binary_annotations.Count));
        foreach (BinaryAnnotation _iter7 in Binary_annotations)
        {
          _iter7.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    if (__isset.debug) {
      field.Name = "debug";
      field.Type = TType.Bool;
      field.ID = 9;
      oprot.WriteFieldBegin(field);
      oprot.WriteBool(Debug);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("Span(");
    bool __first = true;
    if (__isset.trace_id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Trace_id: ");
      __sb.Append(Trace_id);
    }
    if (Name != null && __isset.name) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Name: ");
      __sb.Append(Name);
    }
    if (__isset.id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Id: ");
      __sb.Append(Id);
    }
    if (__isset.parent_id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Parent_id: ");
      __sb.Append(Parent_id);
    }
    if (Annotations != null && __isset.annotations) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Annotations: ");
      __sb.Append(Annotations);
    }
    if (Binary_annotations != null && __isset.binary_annotations) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Binary_annotations: ");
      __sb.Append(Binary_annotations);
    }
    if (__isset.debug) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Debug: ");
      __sb.Append(Debug);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

