/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class BinaryAnnotation : TBase
{
  private string _key;
  private string _value;
  private AnnotationType _annotation_type;
  private Endpoint _host;

  public string Key
  {
    get
    {
      return _key;
    }
    set
    {
      __isset.key = true;
      this._key = value;
    }
  }

  public string Value
  {
    get
    {
      return _value;
    }
    set
    {
      __isset.value = true;
      this._value = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="AnnotationType"/>
  /// </summary>
  public AnnotationType Annotation_type
  {
    get
    {
      return _annotation_type;
    }
    set
    {
      __isset.annotation_type = true;
      this._annotation_type = value;
    }
  }

  public Endpoint Host
  {
    get
    {
      return _host;
    }
    set
    {
      __isset.host = true;
      this._host = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool key;
    public bool value;
    public bool annotation_type;
    public bool host;
  }

  public BinaryAnnotation() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Key = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            Value = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.I32) {
            Annotation_type = (AnnotationType)iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 4:
          if (field.Type == TType.Struct) {
            Host = new Endpoint();
            Host.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("BinaryAnnotation");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Key != null && __isset.key) {
      field.Name = "key";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Key);
      oprot.WriteFieldEnd();
    }
    if (Value != null && __isset.value) {
      field.Name = "value";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Value);
      oprot.WriteFieldEnd();
    }
    if (__isset.annotation_type) {
      field.Name = "annotation_type";
      field.Type = TType.I32;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)Annotation_type);
      oprot.WriteFieldEnd();
    }
    if (Host != null && __isset.host) {
      field.Name = "host";
      field.Type = TType.Struct;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      Host.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("BinaryAnnotation(");
    bool __first = true;
    if (Key != null && __isset.key) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Key: ");
      __sb.Append(Key);
    }
    if (Value != null && __isset.value) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Value: ");
      __sb.Append(Value);
    }
    if (__isset.annotation_type) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Annotation_type: ");
      __sb.Append(Annotation_type);
    }
    if (Host != null && __isset.host) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Host: ");
      __sb.Append(Host== null ? "<null>" : Host.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

