/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public static class zipkinCoreConstants
{
    public static string CLIENT_SEND = "cs";
    public static string CLIENT_RECV = "cr";
    public static string SERVER_SEND = "ss";
    public static string SERVER_RECV = "sr";
    public static string LOCAL_COMPONENT = "lc";
}
