/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

public static class zipkinCoreConstants
{
  public static string CLIENT_SEND = "cs";
  public static string CLIENT_RECV = "cr";
  public static string SERVER_SEND = "ss";
  public static string SERVER_RECV = "sr";
}
